id: Template2
metadata:
  name: Template2
  description: Modules example template
  owner: marcelo.lima@bexsbanco.com.br
  scopes: 
   - global
variables:
- name: regions
  description: A list of AWS regions to deploy into
  type: list
stages:
- id: deploy
  type: deploy
  config:
    clusters: |
      {% for region in regions %}
      - {% module teste ops=region %}
      {% endfor %}

modules:
- id: teste
  usage: Defines a deploy stage cluster using the AWS cloud provider
  variables:
  - name: ops
  definition:
    region: {{ ops }}