id: Template2
metadata:
  name: Template2
  description: Modules example template
  owner: marcelo.lima@bexsbanco.com.br
  scopes: [global]
variables:
- name: regions
  description: A list of AWS regions to deploy into
  type: list
- name: application
  type: string
  default
stages:
 - id: Deploy to Stage
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config:
     manifestSource: text
     account: spinnaker-service-account
     cloudProvider: kubernetes
     notifications:
     - address: "bexspay-team"
       level: "stage"
       type: "slack"
       when: 
       - "stage.failed"
     sendNotifications: true
     moniker:
       app: "teste"
     manifests:
     - apiVersion: v1
       kind: Service
       metadata:
         name: "teste-service"
         namespace: "teste-stage"
       spec:
         type: "ClusterIP"
         selector:
           app:  "app"
         ports:
           - name: "http"
             port: "8080"
             targetPort: "8080"
modules:
- id: teste
  usage: Defines a deploy stage cluster using the AWS cloud provider
  variables:
  - name: ops
  definition:
    region: "{{ ops }}"