id: Template2
schema: "1"
metadata:
  name: Template2
  description: Modules example template
  owner: marcelo.lima@bexsbanco.com.br
  scopes: [global]
variables:
- name: application
  type: string
- name: service
  type: string
  description: the service name without sufix
- name: namespace
  description: the prefix of the namespaces
- name: environments
  description: the list of environments to the deployment. it will be used as namespace sufix
  type: list
stages:
 - id: Deploy to Stage
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config: |
      {% module kubemanifest name=service namespace="stage" %}
modules:
- id: kubema- name: environments
  usage: Kub  description: the list of environments to the deployment
  variables:  type: list
   - name: name
   - name: namespace
  definition:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{name}}-service"
        namespace: "{{name}}-{{namespace}}"
      spec:
        type: "ClusterIP"
        selector:
          app:  "app"
        ports:
          - name: "http"
            port: "8080"
            targetPort: "8080"