id: Template2
schema: "1"
metadata:
  name: Template2
  description: Modules example template
  owner: marcelo.lima@bexsbanco.com.br
  scopes: [global]
variables:
- name: application
  type: string
- name: service
  type: string
  description: the service name without sufix
- name: namespace
  description: the prefix of the namespaces
- name: stage
  type: boolean
  description: deploy on stage
- name: sandbox
  type: boolean
  description: deploy on sandbox
- name: production
  type: boolean
  description: deploy on stage
stages:
 - id: Deploy to Stage
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config: |
      {% module kubemanifest name=service, ns=namespace %}
modules:
- id: kubemanifest
  usage: The k8s deployer
  variables:
   - name: name
   - name: ns
  definition:
    manifestSource: testage
    account: spinnakerstage
    cloudProvider: kubstage
    notifications:
    - address: "bexspastage
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"stage
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{name}}-service"
        namespace: "{{ns}}-stage"
      spec:
        type: "ClusterIP"
        selector:
          app:  "app"
        ports:
          - name: "http"
            port: "8080"
            targetPort: "8080"