id: Template2
schema: "1"
metadata:
  name: Template2
  description: Modules example template
  owner: marcelo.lima@bexsbanco.com.br
  scopes: [global]
variables:
- name: application
  type: string
- name: service
  type: string
  description: the service name without sufix
- name: ns
  description: the prefix of the namespaces
- name: stage
  description: deploy on stage
  type: boolean
  defaultValue: true
- name: sandbox
  description: deploy on sandbox
  type: boolean
  defaultValue: false
- name: production
  defaultValue: false
  description: deploy to production
  type: boolean
  defaultValue: false
stages:
 - id: Deploy to Stage
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config: |
      {% module kubemanifest name=service target="stage" %}
modules:
- id: kubemanifest
  usage: The k8s deployer
  variables:
   - name: name
   - name: target
  definition:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{name}}-service"
        namespace: "{{ns}}-{{target}}"
      spec:
        type: "ClusterIP"
        selector:
          app:  "app"
        ports:
          - name: "http"
            port: "8080"
            targetPort: "8080"