id: Template2
schema: "1"
metadata:
  name: Template2
  description: Modules example template
  owner: marcelo.lima@bexsbanco.com.br
  scopes: [global]
protected: false
variables:
- name: application
  type: string
- name: service
  description: the service name without sufix
  type: string
- name: config
  description: description of the service port
  type: object
  defaultValue:
    ports:
     - port: 8081
       name: "http"
     - port: 6568
       name: "grpc"
    stage:
     configmap:
       - name: env-config-v001
     secret:
       - name: datastore
         mount: "/secret"
         secretName: datastore-cert
    sandbox:
     configmap:
       - name: env-config-v001
     secret:
       - name: datastore
         mount: "/secret"
         secretName: datastore-cert
     ingress:
       fqdn: sandbox.bexs.com.br
       paths:
         - path: /v1/consumers.*
           port: 8081
    prod:
     configmap:
       - name: env-config-v001
     secret:
       - name: datastore
         mount: "/secret"
         secretName: datastore-cert
     ingress:
       fqdn: internals.bexs.com.br
       paths:
         - path: /v1/consumers.*
           port: 8081
- name: stage
  description: deploy on stage
  type: boolean
  defaultValue: true
- name: sandbox
  description: deploy on sandbox
  type: boolean
  defaultValue: false
- name: production
  defaultValue: false
  description: deploy to production
  type: boolean
  defaultValue: false
configuration:
 concurrentExecutions:
  limitConcurrent: true
 triggers: 
  - enabled: true
    job: "{{service}}-service/job/develop"
    master: jenkins
    propertyFile: "spinnaker.properties"
    type: jenkins
stages:
 - id: Deploy to Stage
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifactports
   config: |
      {% module kubemanifest name=service target="stage" ns=application config=config secrets=config.stage.secret maps=config.stage.configmap %}
 - id: Configuring Stage Ingress
   type: deployManifest
   stageTimeoutMs: 60000
   dependsOn:
    - Deploy to Stage
   manifestArtifactAccount: embedded-artifactports
   config: |
     {% module ingress name=service ns=application ingress=config.stage.ingress target="stage" %}
   when:
    - "{{config.stage.ingress != null}}"
 - id: Stage Tests
   dependsOn:
    - Configuring Stage Ingress
   continuePipeline: false
   stageTimeoutMs: 60000
   type: jenkins
   failPipeline: true
   config:
     job: "{{service}}-tests/job/develop"
     master: jenkins
     name: Stage Tests
     notifications:
      - address: "bexspay-team"
        level: "stage"
        type: "slack"
        when: 
        - "stage.complete"
        - "stage.failed"
     sendNotifications: true
 - id: Deploy to Sandbox
   type: deployManifest
   dependsOn:
    - Stage Tests
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config: |
      {% module kubemanifest name=service target="sandbox" ns=application config=config secrets=config.sandbox.secret maps=config.sandbox.configmap %}
 - id: Configuring Sandbox Ingress
   type: deployManifest
   stageTimeoutMs: 60000
   dependsOn:
    - Deploy to Sandbox
   manifestArtifactAccount: embedded-artifactports
   config: |
     {% module ingress name=service ns=application ingress=config.sandbox.ingress target="sandbox" %}
   when:
    - "{{config.sandbox.ingress != null}}"
 - id: Deploy to Prod
   type: deployManifest
   dependsOn:
    - Configuring Sandbox Ingress
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config: |
      {% module kubemanifest name=service target="prod" ns=application config=config secrets=config.prod.secret maps=config.prod.configmap %}
 - id: Configure Production Ingress
   type: deployManifest
   stageTimeoutMs: 60000
   dependsOn:
    - Deploy to Prod
   manifestArtifactAccount: embedded-artifactports
   config: |
     {% module ingress name=service ns=application ingress=config.prod.ingress target="prod" %}
   when:
    - "{{config.stage.ingress != null}}"
modules:
- id: kubemanifest
  usage: The k8s deployer
  variables:
   - name: name
   - name: target
   - name: ns
   - name: config
     type: object
   - name: secrets
     type: object
   - name: maps
     type: object
  definition:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{name}}-service"
        namespace: "{{ns}}-{{target}}"
      spec:
        type: "ClusterIP"
        selector:
          app:  "{{name}}"
        ports: |
          {% for port in config.ports %}
          - {% module portMapping svcname=port.name svcport=port.port %}
          {% endfor %}
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: "{{name}}-deployment"
        namespace: "{{ns}}-{{target}}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{name}}"
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: "sandbox{{name}}"
          spec:sandbox
            containesandboxrs:
              - imagsandboxe: "${ trigger[\"properties\"][\"ci.image\"] }"
                imagsandboxePullPolicy: IfNotPresent
                namesandbox: "{{name}}"
                volumeMounts: |
                  {% for secret in secrets %}
                  - {% module mountVolume secname=secret.name secmount=secret.mount %}
                  {% endfor %}
                envFrom: |
                  {% for map in maps %}
                  - {% module configMap mapname=map.name %}
                  {% endfor %}
            restartPolicy: "Always"
            volumes: |
              {% for secret in secrets %}
              - {% module secretMapping secname=secret.name seccert=secret.secretName %}
              {% endfor %}
- id: portMapping
  variables:
   - name: svcport
   - name: svcname
  definition:
    name: "{{svcname}}"
    port: "{{svcport}}" 
    targetPort: "{{svcport}}"
- id: mountVolume
  variables:
   - name: secname
   - name: secmount
  definition:
    name: "{{secname}}"
    mountPath: "{{secmount}}"
- id: secretMapping
  variables:
   - name: secname
   - name: seccert
  definition:
    name: "{{sesandbox}}"
    secret:
        secretNsandbox"{{seccert}}"
- id: configMapsandbox
  variables:
   - name: mapname
  definition:
    configMapRef:
      name: "{{mapname}}"
      
- id: ingress
  variables:
    - name: name
    - name: ns
    - name: target
    - name: ingress
      type: object
  definition:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when:   
      - "stage.failed"
    sendNotifications: true
    moniker:  
      app: "{{ns}}"
    manifests:
     - apiVersion: extensions/v1beta1
       kind: Ingress
       metadata:  
         annotations:
           kubernetes.io/ingress.class: istio
         name: "{{name}}-ingress"
         namespace: "{{ns}}-{{target}}"
       spec:
         rules: |
           {% for item in ingress.paths %}
           - {% module ingressItem inghost=ingress.fqdn name=name %}
           {% endfor %}
- id: ingressItem
  variables:
   - name: inghost
   - name: name
  definition:
    host: "{{inghost}}"
    http:
      paths:
        - backend:
            serviceName: "{{name}}-service"
            servicePort: 8080
          path: /v1/payments.*