id: configuration
schema: "1"
metadata:
  description: Create Sevice to be managed by spinnaker
  owner: marcelo.lima@bexsbanco.com.br
  scopes: [global]
protected: false
variables: 
  - name: namespace
  - name: application
  - name: ports
    type: object
    defaultValue:
      ports:
       - port: 8081
         name: "http"
       - port: 6568
         name: "grpc"
stages:
- id: Configuring Service at Stage
  type: deployManifest
  stageTimeoutMs: 30000
  manifestArtifactAccount: embedded-artifact
  config:
    manifestSource: text
    account: stage
    cloudProvider: kubernetes
    notifications:
    - address: "pay-cicd"
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{application}}-service"
        namespace: "{{namespace}}"
      spec:
        type: "ClusterIP"
        selector:
          app:  "{{namespace}}"
        ports: |
          "{{ port }}"
         
          