schema: "1"
id: services-template
metadata:
 description: Service Template. Generates Deployment, Replicaset and POD
 name: Service Deployment Template
 owner: marcelo.lima@bexsbanco.com.br
 scope: 
  - global
protected: false
variables:
 - name: namespace
   description: The target namespace where the service will be deployed
   defaultValue: payments
 - name: service_name
   description: The service name
 - name: configurationVersion
   description: The environment configmap version
 - name: jenkinsjob
   description: The Jenkins job path
   defaultValue: payment-service/job/develop
 - name: application
   description: The application name
   defaultValue: paymentstage
 - name: jenkins_test_job
   description: The Jenkins job path to the automated test
   defaultValue: payments-tests/job/develop
 - name: service_port_name
   description: The name of the service port
   defaultValue: http
 - name: service_port
   description: the external service port
   defaultValue: 8080
 - name: balancer
   description: The type of the loadbalancer
   defaultValue: ClusterIP
configuration:
 concurrentExecutions:
  limitConcurrent: true
 triggers: 
  - enabled: true
    job: "{{jenkinsjob}}"
    master: jenkins
    propertyFile: "spinnaker.properties"
    type: jenkins
stages:
 - id: Deploy to Stage
   refId: 1
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.complete"
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{service_name}}-service"
        namespace: "{{namespace}}-stage"
      spec:
        type: "{{balancer}}"
        selector:
          app:  "{{service_name}}"
        ports:
          - name: "{{service_port_name}}"
            port: "{{service_port}}"
            targetPort: "{{service_port}}"
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: "{{service_name}}-deployment-${ trigger[\"buildNumber\"] }"
        namespace: "{{namespace}}-stage"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{service_name}}"
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: "{{service_name}}"
          spec:
            containers:
              - image: "${ trigger[\"properties\"][\"ci.image\"] }"
                imagePullPolicy: IfNotPresent
                name: "{{service_name}}"
                volumeMounts: 
                  - mountPath: /secret
                    name: datastore
                envFrom:
                  - configMapRef:
                      name: "env-config-{{configurationVersion}}"
            restartPolicy: "Always"
            volumes:
              - name: datastore
                secret:
                  secretName: datastore-cert
 - id: Automated Tests
   refId: 2
   dependsOn:
    - Deploy to Stage
   continuePipeline: false
   stageTimeoutMs: 60000
   type: jenkins
   failPipeline: true
   config:
     job: "{{jenkins_test_job}}"
     master: jenkins
     name: Automated Tests
 - id: Update Sandbox
   refId: 3
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.complete"
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{service_name}}-service"
        namespace: "{{namespace}}-sandbox"
      spec:
        type: "{{balancer}}"
        selector:
          app:  "{{service_name}}"
        ports:
          - name: "{{service_port_name}}"
            port: "{{service_port}}"
            targetPort: "{{service_port}}"
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: "{{service_name}}-deployment-${ trigger[\"buildNumber\"] }"
        namespace: "{{namespace}}-sandbox"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{service_name}}"
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: "{{service_name}}"
          spec:
            containers:
              - image: "${ trigger[\"properties\"][\"ci.image\"] }"
                imagePullPolicy: IfNotPresent
                name: "{{service_name}}"
                volumeMounts: 
                  - mountPath: /secret
                    name: datastore
                envFrom:
                  - configMapRef:
                      name: "env-config-{{configurationVersion}}"
            restartPolicy: "Always"
            volumes:
              - name: datastore
                secret:
                  secretName: datastore-cert