schema: "1"
id: services-template
metadata:
 description: Service Template. Generates Deployment, Replicaset and POD
 name: Service Deployment Template
 owner: marcelo.lima@bexsbanco.com.br
 scope: 
  - global
protected: false
variables:
 - name: namespace
   description: The target namespace where the service will be deployed
   defaultValue: payments
 - name: service_name
   description: The service name
 - name: ports
   descripton: information about service ports
   type: object
   example: |
    - name: http
      port: 8080
      target: 8080
 - name: stageConfigVersion
   description: The environment configmap version
 - name: sandboxConfigVersion
   description: The environment configmap version
 - name: productionConfigVersion
   description: The production configmap version
 - name: jenkinsjob
   description: The Jenkins job path
   defaultValue: payment-service/job/develop
 - name: application
   description: The application name
   defaultValue: paymentstage
 - name: jenkins_test_job
   description: The Jenkins job path to the automated test
   defaultValue: payments-tests/job/develop
 - name: balancer
   description: The type of the loadbalancer
   defaultValue: ClusterIP
configuration:
 concurrentExecutions:
  limitConcurrent: true
 triggers: 
  - enabled: true
    job: "{{jenkinsjob}}"
    master: jenkins
    propertyFile: "spinnaker.properties"
    type: jenkins
stages:
 - id: Deploy to Stage
   refId: 1
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{service_name}}-service"
        namespace: "{{namespace}}-stage"
      spec:
        type: "{{balancer}}"
        selector:
          app:  "{{service_name}}"
        ports:
         
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: "{{service_name}}-deployment"
        namespace: "{{namespace}}-stage"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{service_name}}"
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: "{{service_name}}"
          spec:
            containers:
              - image: "${ trigger[\"properties\"][\"ci.image\"] }"
                imagePullPolicy: IfNotPresent
                name: "{{service_name}}"
                volumeMounts: 
                  - mountPath: /secret
                    name: datastore
                envFrom:
                  - configMapRef:
                      name: "env-config-{{stageConfigVersion}}"
            restartPolicy: "Always"
            volumes:
              - name: datastore
                secret:
                  secretName: datastore-cert
 - id: Automated Tests
   refId: 2
   dependsOn:
    - Deploy to Stage
   continuePipeline: false
   stageTimeoutMs: 60000
   type: jenkins
   failPipeline: true
   config:
     job: "{{jenkins_test_job}}"
     master: jenkins
     name: Automated Tests
     notifications:
      - address: "bexspay-team"
        level: "stage"
        type: "slack"
        when: 
        - "stage.complete"
        - "stage.failed"
     sendNotifications: true
 - id: Update Sandbox
   refId: 3
   dependsOn:
    - Automated Tests
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{service_name}}-service"
        namespace: "{{namespace}}-sandbox"
      spec:
        type: "{{balancer}}"
        selector:
          app:  "{{service_name}}"
        ports:
          - name: "{{service_port_name}}"
            port: "{{service_port}}"
            targetPort: "{{service_port}}"
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: "{{service_name}}-deployment"
        namespace: "{{namespace}}-sandbox"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{service_name}}"
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: "{{service_name}}"      strategy: highlander

          spec:
            containers:
              - image: "${ trigger[\"properties\"][\"ci.image\"] }"
                imagePullPolicy: IfNotPresent
                name: "{{service_name}}"
                volumeMounts: 
                  - mountPath: /secret
                    name: datastore
                envFrom:
                  - configMapRef:
                      name: "env-config-{{sandboxConfigVersion}}"
            restartPolicy: "Always"
            volumes:
              - name: datastore
                secret:
                  secretName: datastore-cert
 - id: Update Production
   refId: 4
   dependsOn:
    - Update Sandbox
   type: deployManifest
   stageTimeoutMs: 60000
   manifestArtifactAccount: embedded-artifact
   config:
    manifestSource: text
    account: spinnaker-service-account
    cloudProvider: kubernetes
    notifications:
    - address: "bexspay-team"
      level: "stage"
      type: "slack"
      when: 
      - "stage.complete"
      - "stage.failed"
    sendNotifications: true
    moniker:
      app: "{{application}}"
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: "{{service_name}}-service"
        namespace: "{{namespace}}-prod"
      spec:
        type: "{{balancer}}"
        selector:
          app:  "{{service_name}}"
        ports:
          - name: "{{service_port_name}}"
            port: "{{service_port}}"
            targetPort: "{{service_port}}"
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: "{{service_name}}-deployment"
        namespace: "{{namespace}}-prod"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{service_name}}"
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: "{{service_name}}"
          spec:
            containers:
              - image: "${ trigger[\"properties\"][\"ci.image\"] }"
                imagePullPolicy: IfNotPresent
                name: "{{service_name}}"
                volumeMounts: 
                  - mountPath: /secret
                    name: datastore
                envFrom:
                  - configMapRef:
                      name: "env-config-{{productionConfigVersion}}"
            restartPolicy: "Always"
            volumes:
              - name: datastore
                secret:
                  secretName: datastore-cert
modules:
 - id: kubeports
   usage: define service structure
   variables:
    - name: name
      description: service name
    - name: port
      description: the service port
   definition:
     name: "{{ name }}"
            port: "{{ port }}"
            targetPort: "{{ port }}"